package services

import (
	"context"
	"encoding/json"
	"fmt"
	"insight-engine-backend/models"
	"strings"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

type NLDashboardService struct {
	aiService *AIService
}

func NewNLDashboardService(aiService *AIService) *NLDashboardService {
	return &NLDashboardService{aiService: aiService}
}

// GenerateDashboard creates a dashboard configuration from natural language
func (s *NLDashboardService) GenerateDashboard(ctx context.Context, text string, userID string, workspaceID string) (*models.Dashboard, error) {
	provider, err := s.aiService.GetDefaultProvider(userID)
	if err != nil {
		return nil, fmt.Errorf("failed to get AI provider: %v", err)
	}

	prompt := fmt.Sprintf(`
Generate a dashboard layout JSON for a business intelligence dashboard based on this request: "%s".
The layout should be a list of widgets with x, y, w, h, type (chart, metric, text), title, and query configuration.
Return ONLY valid JSON.
`, text)

	// Context for AI
	aiCtx := map[string]interface{}{
		"type": "dashboard_generation",
	}

	aiReq, err := s.aiService.Generate(ctx, provider.ID, userID, prompt, aiCtx)
	if err != nil {
		return nil, err
	}

	if aiReq == nil || aiReq.Response == nil {
		return nil, fmt.Errorf("empty response from AI")
	}

	response := *aiReq.Response

	// Clean up response
	cleanResponse := strings.TrimPrefix(response, "```json")
	cleanResponse = strings.TrimPrefix(cleanResponse, "```")
	cleanResponse = strings.TrimSuffix(cleanResponse, "```")
	cleanResponse = strings.TrimSpace(cleanResponse)

	layoutJSON := []byte(cleanResponse)
	// Validate JSON
	if !json.Valid(layoutJSON) {
		return nil, fmt.Errorf("invalid JSON generated by AI")
	}

	layout := datatypes.JSON(layoutJSON)
	desc := "Auto-generated from prompt: " + text

	parsedWorkspaceID, err := uuid.Parse(workspaceID)
	if err != nil {
		return nil, fmt.Errorf("invalid workspace ID: %w", err)
	}
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	dashboard := &models.Dashboard{
		ID:           uuid.New(),
		CollectionID: parsedWorkspaceID, // Mapping to CollectionID as per previous findings
		UserID:       parsedUserID,
		Name:         "AI Dashboard: " + text,
		Description:  &desc,
		Layout:       &layout,
		IsPublic:     false,
	}

	return dashboard, nil
}
