run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
