openapi: 3.1.0
info:
  title: InsightEngine API
  description: Business Intelligence Platform API
  version: 1.0.0
  contact:
    name: InsightEngine Support
    email: support@insightengine.ai
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://api.insightengine.ai
    description: Production server

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'

  /auth/login:
    post:
      summary: Authenticate user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /queries:
    get:
      summary: Get user's queries
      tags:
        - Queries
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of queries
          content:
            application/json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      $ref: '#/components/schemas/Query'
    post:
      summary: Create a new query
      tags:
        - Queries
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryCreate'
      responses:
        '201':
          description: Query created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Query'
        '400':
          $ref: '#/components/responses/BadRequest'

  /queries/{id}/run:
    post:
      summary: Execute a saved query
      tags:
        - Queries
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Query results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResult'
        '404':
          $ref: '#/components/responses/NotFound'

  /connections:
    get:
      summary: Get user's connections
      tags:
        - Connections
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of connections
          content:
            application/json:
              schema:
                type: object
                properties:
                  connections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Connection'
    post:
      summary: Create a new connection
      tags:
        - Connections
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionCreate'
      responses:
        '201':
          description: Connection created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connection'
        '400':
          $ref: '#/components/responses/BadRequest'

  /dashboards:
    get:
      summary: Get user's dashboards
      tags:
        - Dashboards
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of dashboards
          content:
            application/json:
              schema:
                type: object
                properties:
                  dashboards:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dashboard'
    post:
      summary: Create a new dashboard
      tags:
        - Dashboards
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DashboardCreate'
      responses:
        '201':
          description: Dashboard created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dashboard'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRegistration:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          format: email
          description: User's email address
        password:
          type: string
          format: password
          minLength: 8
          description: User's password
        name:
          type: string
          description: User's full name

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT token for authentication
        user:
          $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        email:
          type: string
          format: email
        name:
          type: string
          description: User's full name
        createdAt:
          type: string
          format: date-time

    Query:
      type: object
      properties:
        id:
          type: string
          description: Unique query identifier
        name:
          type: string
          description: Query name
        sql:
          type: string
          description: SQL query string
        connectionId:
          type: string
          description: Associated connection ID
        userId:
          type: string
          description: Owner user ID
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    QueryCreate:
      type: object
      required:
        - name
        - sql
        - connectionId
      properties:
        name:
          type: string
        sql:
          type: string
        connectionId:
          type: string
        description:
          type: string

    QueryResult:
      type: object
      properties:
        columns:
          type: array
          items:
            type: string
        rows:
          type: array
          items:
            type: array
            items:
              type: {}
        executionTime:
          type: number
          description: Query execution time in milliseconds

    Connection:
      type: object
      properties:
        id:
          type: string
          description: Unique connection identifier
        name:
          type: string
          description: Connection name
        type:
          type: string
          enum: [postgresql, mysql, sqlserver, oracle, mongodb, bigquery, snowflake]
          description: Database type
        config:
          type: object
          description: Connection configuration (may be encrypted)
        userId:
          type: string
          description: Owner user ID
        isActive:
          type: boolean
          description: Whether the connection is active
        createdAt:
          type: string
          format: date-time

    ConnectionCreate:
      type: object
      required:
        - name
        - type
        - config
      properties:
        name:
          type: string
        type:
          type: string
          enum: [postgresql, mysql, sqlserver, oracle, mongodb, bigquery, snowflake]
        config:
          type: object
          description: Connection parameters

    Dashboard:
      type: object
      properties:
        id:
          type: string
          description: Unique dashboard identifier
        name:
          type: string
          description: Dashboard name
        description:
          type: string
          description: Dashboard description
        userId:
          type: string
          description: Owner user ID
        config:
          type: object
          description: Dashboard configuration
        isPublic:
          type: boolean
          description: Whether the dashboard is publicly accessible
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    DashboardCreate:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        isPublic:
          type: boolean
          default: false

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid request parameters"
    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Authentication required"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Resource not found"
    Conflict:
      description: Conflict - resource already exists
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Resource already exists"

security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: User authentication and registration
  - name: Queries
    description: Query management and execution
  - name: Connections
    description: Database connection management
  - name: Dashboards
    description: Dashboard creation and management
  - name: Collections
    description: Organizing queries and dashboards
  - name: Analytics
    description: Advanced analytics features